# Generated by Django 4.2.5 on 2023-09-08 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reminders', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reminder',
            name='date_time',
        ),
        migrations.RemoveField(
            model_name='reminder',
            name='text',
        ),
        migrations.AddField(
            model_name='reminder',
            name='date',
            field=models.DateField(default='2023-09-08'),
        ),
        migrations.AddField(
            model_name='reminder',
            name='phone_number',
            field=models.CharField(default='254714805460', max_length=15),
        ),
        migrations.AddField(
            model_name='reminder',
            name='time',
            field=models.TimeField(default='09:23'),
        ),
        migrations.AddField(
            model_name='reminder',
            name='title',
            field=models.CharField(default='reminder', max_length=100),
        ),
    ]
