# Generated by Django 4.2.5 on 2023-09-08 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reminders', '0003_alter_reminder_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reminder',
            name='time',
            field=models.TimeField(default='09:25'),
        ),
    ]
