# Generated by Django 4.2.5 on 2023-09-08 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reminders', '0004_alter_reminder_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reminder',
            name='time',
            field=models.TimeField(),
        ),
    ]
