# Generated by Django 4.2.5 on 2023-09-08 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reminders', '0002_remove_reminder_date_time_remove_reminder_text_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reminder',
            name='time',
            field=models.TimeField(default='09:23'),
        ),
    ]
